<?php

namespace AppBundle\Repository;

/**
 * VideoStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoStudyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findForVideo($vid) {
		$query=$this->getEntityManager()->createQuery('Select vs, s, v from AppBundle:VideoStudy vs JOIN vs.study s JOIN vs.video v where v.id=:vid order by s.protocol');
		$query->setParameter('vid', $vid);
		try {
			return $query->getResult();
		}
		catch(\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
	
	
}
