<?php

namespace AppBundle\Repository;

/**
 * VideoStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoStudyRepository extends \Doctrine\ORM\EntityRepository
{
}
