<?php

namespace AppBundle\Repository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends \Doctrine\ORM\EntityRepository
{
	public function listVideoswithLanguage() {
		$query=$this->getEntityManager()->createQuery('Select v, l from AppBundle:Video v  JOIN v.language l');
		try {
			return $query->getResult();
		}
		catch(\Doctrine\ORM\NoResultException $e) {
			return null;			
		}
	}
	
	public function listVideoswithLanguageTranscript() {
		$query=$this->getEntityManager()->createQuery('Select v, l, t from AppBundle:Video v  JOIN v.language l LEFT JOIN v.transcripts t');
		try {
			return $query->getResult();
		}
		catch(\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
	
	
	
}
