<?php

namespace AppBundle\Repository;

/**
 * VideoStudyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoStudyRepository extends \Doctrine\ORM\EntityRepository
{
	public function findForVideo() {
		$query=$this->getEntityManager()->createQuery('Select vs, s from AppBundle:VideoStudy vs JOIN vs.study s order by s.protocol');
		try {
			return $query->getResult();
		}
		catch(\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
	
	
}
